
import { Region, FolkStory } from './types';

export const STORY_DATASET: FolkStory[] = [
  // BENGALI
  { id: "bn-1", title: "Behula and Lakhindar", region: Region.Bengali, type: "Epic Devotional Tragedy", era: "13th–16th Century", theme: ["Marital Devotion", "Faith", "Triumph over Fate"], summary: "Behula marries Lakhindar, who dies from a snakebite on their wedding night due to a curse by Goddess Manasa. Refusing to accept fate, Behula carries his body on a raft for months, facing immense hardships. Her unwavering devotion moves the gods, and Lakhindar is restored to life." },
  { id: "bn-2", title: "Manasa Devi Legends", region: Region.Bengali, type: "Goddess Mythology", era: "Ancient", theme: ["Nature Worship", "Pride vs Devotion", "Divine Power"], summary: "Manasa, the snake goddess and daughter of Shiva, demands worship from the merchant Chand Sadagar. When he refuses, she destroys his wealth and family through serpents. Ultimately, devotion triumphs, reflecting Bengal’s reverence for nature deities and riverine life." },
  { id: "bn-3", title: "Satya Narayan Katha", region: Region.Bengali, type: "Devotional Folk Tale", era: "Ancient (Puranic Roots)", theme: ["Gratitude", "Vows", "Divine Justice"], summary: "A merchant who forgets his vow to worship Satya Narayan after gaining wealth loses everything. When he remembers his promise and performs the ritual, prosperity returns, emphasizing faith, gratitude, and moral responsibility." },
  { id: "bn-4", title: "Lalkamal and Neelkamal", region: Region.Bengali, type: "Fairy Tale Epic", era: "Ancient Oral Tradition", theme: ["Brotherhood", "Courage", "Adventure"], summary: "Brothers Lalkamal and Neelkamal, born through magical means, embark on daring adventures. Facing demons and rescuing princesses, they use wit and bravery to overcome evil, teaching courage and loyalty." },
  { id: "bn-5", title: "Gopal Bhar Stories", region: Region.Bengali, type: "Humor and Wisdom Folklore", era: "18th Century (Oral Roots)", theme: ["Cleverness", "Satire", "Moral Insight"], summary: "Gopal Bhar, the witty court jester of Raja Krishnachandra, uses intelligence and humor to expose arrogance and hypocrisy. His tales emphasize wisdom over power and are beloved across Bengal." },
  { id: "bn-6", title: "Pret Katha (Ghost Legends)", region: Region.Bengali, type: "Supernatural Folklore", era: "Ancient", theme: ["Rituals", "Fear", "Moral Warning"], summary: "Bengali ghost stories describe spirits like Brahman pretas, Shakchunni, Mechho Bhoot, and Skondhokata. These tales warn against neglecting rituals and reflect Bengal’s rich supernatural folklore." },
  { id: "bn-7", title: "The Origin of Opium (Afsos-er Kahini)", region: Region.Bengali, type: "Explanatory Moral Legend", era: "Ancient", theme: ["Temptation", "Excess", "Moral Consequences"], summary: "A king or sage discovers the effects of opium through divine or accidental means. While its benefits are revealed, the tale warns against addiction and excess, blending myth with moral teaching." },
  { id: "bn-8", title: "Chand Sadagar and the Six Queens", region: Region.Bengali, type: "Devotional Epic", era: "Medieval", theme: ["Fertility", "Pride", "Divine Retribution"], summary: "Chand Sadagar, a proud merchant with six queens, remains childless due to his refusal to worship Manasa. Only after devotion does prosperity return, reinforcing humility and faith." },
  { id: "bn-9", title: "The Boy with Seven Mothers", region: Region.Bengali, type: "Folk Motif Legend", era: "Ancient", theme: ["Identity", "Loyalty", "Hidden Nobility"], summary: "Raised by seven mothers, a young boy faces trials that reveal his true worth and noble destiny. The story explores adoption, devotion, and destiny." },
  { id: "bn-10", title: "Rakhosh and Human Heroes", region: Region.Bengali, type: "Demon-Slaying Folk Tales", era: "Ancient", theme: ["Good vs Evil", "Bravery", "Intelligence"], summary: "Rakhosh tales describe man-eating giants defeated by clever children, princes, or devotees using wit and courage. These stories teach resilience and the triumph of good over evil." },

  // GUJARATI
  { id: "gj-1", title: "Narsinh Mehta and Sudama", region: Region.Gujarati, type: "Devotional Legend", era: "15th Century", theme: ["Friendship", "Bhakti", "Humility"], summary: "Narsinh Mehta, the great Gujarati Bhakti poet, narrates the story of Sudama, a poor Brahmin and childhood friend of Lord Krishna. Despite Sudama’s poverty, Krishna welcomes him with love and blesses him. The tale highlights pure devotion, humility, and divine grace." },
  { id: "gj-2", title: "Rani no Hajiro (The Queen’s Tomb)", region: Region.Gujarati, type: "Historical Legend", era: "16th Century", theme: ["Loyalty", "Sacrifice", "Honor"], summary: "This legend tells of a devoted queen whose loyalty and virtue were honored through the construction of Rani no Hajiro in Ahmedabad. The story reflects sacrifice, dignity, and the respect given to royal women in Gujarati history." },
  { id: "gj-3", title: "Hinglaj Mata and the Shepherd", region: Region.Gujarati, type: "Goddess Legend", era: "Ancient", theme: ["Faith", "Protection", "Divine Justice"], summary: "Hinglaj Mata, revered by pastoral communities, protects her devotees from harm. Folk stories describe shepherds receiving divine aid after showing unwavering faith, emphasizing protection and motherly compassion." },
  { id: "gj-4", title: "The Clever Barber of Gujarat", region: Region.Gujarati, type: "Folk Wisdom Tale", era: "Medieval", theme: ["Intelligence", "Justice", "Common Sense"], summary: "A clever barber uses wit and presence of mind to solve problems and expose injustice in his village. The story celebrates intelligence over power and highlights folk wisdom prevalent in Gujarati rural traditions." },
  { id: "gj-5", title: "Jasma Odan", region: Region.Gujarati, type: "Tragic Folk Legend", era: "Medieval", theme: ["Chastity", "Honor", "Sacrifice"], summary: "Jasma Odan, a virtuous woman, resists the advances of a powerful ruler and sacrifices her life to protect her honor. Her story is remembered as a symbol of chastity, courage, and moral strength in Gujarati folklore." },
  { id: "gj-6", title: "Meghani’s Folk Heroes", region: Region.Gujarati, type: "Heroic Folklore", era: "Oral Tradition", theme: ["Bravery", "Resistance", "Folk Justice"], summary: "Collected and popularized by folklorist Jhaverchand Meghani, these stories celebrate local heroes who stood against oppression and injustice, reflecting the bravery and resilience of Gujarati society." },
  { id: "gj-7", title: "The Story of Sati Toral", region: Region.Gujarati, type: "Devotional Folk Legend", era: "Medieval", theme: ["Devotion", "Spiritual Strength", "Renunciation"], summary: "Sati Toral renounces royal life after spiritual awakening and embraces devotion. Her life story emphasizes detachment from material wealth and the power of inner realization." },
  { id: "gj-8", title: "Ashapura Mata Legends", region: Region.Gujarati, type: "Clan Goddess Legend", era: "Ancient", theme: ["Protection", "Faith", "Community Identity"], summary: "Ashapura Mata, the kuldevi of several Gujarati communities, protects her devotees and fulfills wishes. Her legends emphasize collective faith, identity, and divine guardianship." },
  { id: "gj-9", title: "The Merchant and the Monkey", region: Region.Gujarati, type: "Moral Folk Tale", era: "Ancient", theme: ["Greed", "Wisdom", "Consequences"], summary: "A merchant’s greed leads him into trouble when he underestimates a clever monkey. The tale teaches the dangers of arrogance and the value of humility and wisdom." },
  { id: "gj-10", title: "Bhavai Folk Theatre Legends", region: Region.Gujarati, type: "Performance Folklore", era: "Medieval", theme: ["Social Critique", "Humor", "Justice"], summary: "Bhavai folk theatre presents humorous yet sharp stories addressing social evils, corruption, and inequality. These legends use satire and performance to educate and reform society." },

  // KERALA
  { id: "kl-1", title: "Parasurama Creates Kerala", region: Region.Kerala, type: "Creation Myth", era: "Ancient (Puranic)", theme: ["Creation", "Sacred Geography", "Divine Will"], summary: "Parasurama, the sixth avatar of Vishnu, throws his axe into the sea after intense penance. The land that rises from the ocean becomes Kerala, known as Parasurama Kshetra. He establishes temples and settlements, explaining Kerala’s coastal geography and sacred identity." },
  { id: "kl-2", title: "Mahabali and Onam (King Maveli)", region: Region.Kerala, type: "Festival Legend", era: "Ancient (Puranic)", theme: ["Humility", "Equality", "Prosperity"], summary: "King Mahabali rules Kerala with justice and equality. Disguised as the dwarf Vamana, Vishnu asks for three paces of land and sends Mahabali to the netherworld. Moved by his devotion, Vishnu grants Mahabali the right to visit Kerala every year during Onam." },
  { id: "kl-3", title: "Lord Ayyappa (Manikandan) and Sabarimala", region: Region.Kerala, type: "Devotional Legend", era: "Ancient–Medieval", theme: ["Dharma", "Celibacy", "Equality"], summary: "Ayyappa, born to Shiva and Vishnu (as Mohini), is found by the Pandalam king and raised as Manikandan. He defeats the demoness Mahishi and establishes his temple at Sabarimala. His legend emphasizes discipline, devotion, and equality among devotees." },
  { id: "kl-4", title: "Theyyam Legends", region: Region.Kerala, type: "Ritual Folklore", era: "Ancient (Pre-Vedic)", theme: ["Justice", "Ancestral Worship", "Social Order"], summary: "Theyyam is a ritual performance where dancers embody deities, heroes, or spirits such as Kuttichathan and Gulikan. These legends preserve oral histories, resolve social disputes, and represent justice and protection through divine possession." },
  { id: "kl-5", title: "Mudiyettu: Kali vs Darika", region: Region.Kerala, type: "Ritual Epic", era: "Ancient", theme: ["Good vs Evil", "Devotion", "Community"], summary: "Mudiyettu is a ritual dance-drama depicting Goddess Bhadrakali’s battle with the demon Darika. Her victory restores cosmic order. The performance symbolizes moral righteousness and is central to temple traditions in Kerala." },
  { id: "kl-6", title: "Naranathu Bhrantan", region: Region.Kerala, type: "Philosophical Folk Tale", era: "Medieval", theme: ["Impermanence", "Detachment", "Wisdom"], summary: "Naranathu Bhrantan repeatedly pushes a stone uphill only to let it roll back down. His actions symbolize the futility of material ambition and the impermanent nature of human achievements." },
  { id: "kl-7", title: "Kayamkulam Kochunni", region: Region.Kerala, type: "Folk Hero Legend", era: "Medieval", theme: ["Justice", "Resistance", "Cleverness"], summary: "Kayamkulam Kochunni, a legendary thief, robs wealthy oppressors and helps the poor. Known for clever disguises and escapes, he represents resistance to injustice and folk heroism." },
  { id: "kl-8", title: "Yakshi Legends", region: Region.Kerala, type: "Nature Spirit Folklore", era: "Ancient", theme: ["Nature", "Cautionary Morals", "Female Power"], summary: "Yakshis are supernatural female spirits associated with sacred groves and trees. Some protect the land, while others punish greed and desire. These legends reflect reverence for nature and moral warnings." },
  { id: "kl-9", title: "Kadamattathu Kathanar", region: Region.Kerala, type: "Mystic Hero Legend", era: "9th Century", theme: ["Faith", "Occult Wisdom", "Protection"], summary: "Kadamattathu Kathanar, a legendary priest-sorcerer, is known for performing miracles and protecting villages from dark forces. His tales blend spirituality, magic, and moral courage." },
  { id: "kl-10", title: "Pakkanar and the Twelve Children", region: Region.Kerala, type: "Moral Folk Legend", era: "Ancient", theme: ["Egalitarianism", "Virtue", "Destiny"], summary: "Pakkanar, a humble figure, fathers twelve sons who each excel in different skills. Their success teaches that virtue and destiny matter more than caste or birth, reflecting Kerala’s egalitarian values." },

  // PUNJABI
  { id: "pb-1", title: "Heer Ranjha", region: Region.Punjabi, type: "Tragic Romance", era: "Pre-1600s", theme: ["Love", "Spirituality", "Society"], summary: "Heer, a beautiful girl from a wealthy Jat family, falls in love with Ranjha, a flute-playing wanderer. Their love defies social norms, leading to tragic separation and death. The tale symbolizes selfless spiritual love in Punjabi Sufi tradition." },
  { id: "pb-2", title: "Sohni Mahiwal", region: Region.Punjabi, type: "Tragic Romance", era: "Medieval", theme: ["Forbidden Love", "Sacrifice", "Loyalty"], summary: "Sohni swims across the Chenab river using an earthen pot to meet Mahiwal. Betrayed by her sister-in-law with a raw clay pot, she drowns, and Mahiwal dies with her, symbolizing ultimate sacrifice." },
  { id: "pb-3", title: "Mirza Sahiban", region: Region.Punjabi, type: "Tragic Romance", era: "16th–17th Century", theme: ["Trust", "Fate", "Betrayal"], summary: "Mirza elopes with Sahiban. Sahiban breaks Mirza's arrows to prevent her brothers' death, leaving him defenseless. Mirza is killed, highlighting the tragic conflict between family loyalty and romantic love." },
  { id: "pb-4", title: "Sassi Punnun", region: Region.Punjabi, type: "Tragic Romance", era: "Medieval", theme: ["Endurance", "Separation", "Devotion"], summary: "Sassi dies in the desert searching for her husband Punnun, who was kidnapped by his brothers. The tale represents enduring love and the agony of separation." },
  { id: "pb-5", title: "Puran Bhagat", region: Region.Punjabi, type: "Devotional Legend", era: "Ancient", theme: ["Forgiveness", "Faith", "Spirituality"], summary: "Prince Puran, falsely accused and left for dead, survives and becomes a bhagat. His eventual forgiveness of his family emphasizes spiritual transformation and resilience." },
  { id: "pb-6", title: "Raja Rasalu", region: Region.Punjabi, type: "Heroic Legend", era: "Ancient", theme: ["Bravery", "Justice", "Wisdom"], summary: "Raja Rasalu battles demons and solves riddles in ancient folklore, celebrating courage and moral victory against tyranny." },
  { id: "pb-7", title: "Dulla Bhatti", region: Region.Punjabi, type: "Folk Hero Legend", era: "16th Century", theme: ["Resistance", "Justice", "Heroism"], summary: "A Robin Hood figure who fought Mughal oppression and rescued girls from slavery. Remembered during Lohri as a symbol of resistance." },
  { id: "pb-8", title: "Gugga Pir", region: Region.Punjabi, type: "Folk Deity Legend", era: "Medieval", theme: ["Protection", "Faith", "Rural Life"], summary: "A prince-turned-deity who protects farmers and cattle from snakes. His story blends miracles with rural faith." },
  { id: "pb-9", title: "Sarwan", region: Region.Punjabi, type: "Moral Tragedy", era: "Ancient", theme: ["Filial Piety", "Devotion", "Tragedy"], summary: "A son devoted to his blind parents is accidentally killed by a king's arrow. It emphasizes the sacred duty toward parents." },
  { id: "pb-10", title: "Dhanna Bhagat", region: Region.Punjabi, type: "Devotional Legend", era: "Medieval", theme: ["Innocent Faith", "Bhakti", "Miracles"], summary: "A simple farmer whose pure, innocent faith in a stone idol brings divine presence, proving that sincere devotion transcends rituals." },

  // TAMIL
  { id: "tm-1", title: "Kannagi and Kovalan (Silappadikaram)", region: Region.Tamil, type: "Epic Tragedy", era: "1st–3rd Century CE", theme: ["Justice", "Chastity", "Moral Law"], summary: "Kannagi proves her husband's innocence after he is wrongly executed. Her rage burns Madurai, and she ascends as a goddess of justice and female power." },
  { id: "tm-2", title: "Murugan and Surapadman", region: Region.Tamil, type: "Mythological Legend", era: "Sangam Period", theme: ["Valor", "Youth", "Divine Protection"], summary: "The god Murugan defeats the demon Surapadman, transforming him into a peacock. It highlights courage and Murugan’s central place in Tamil identity." },
  { id: "tm-3", title: "Agastya and Vindhya", region: Region.Tamil, type: "Sage Legend", era: "Ancient", theme: ["Humility", "Knowledge", "Cultural Origins"], summary: "Sage Agastya humbles the mountains to move south, bringing Vedic knowledge and establishing the foundations of Tamil grammar and medicine." },
  { id: "tm-4", title: "Annanmar Kathai", region: Region.Tamil, type: "Folk Epic", era: "Ancient Oral Tradition", theme: ["Brotherhood", "Honor", "Fate"], summary: "A legendary epic of two heroic brothers who protect their village and sister, reflecting deep-rooted values of loyalty and destiny." },
  { id: "tm-5", title: "Manu Neethi Cholan", region: Region.Tamil, type: "Justice Legend", era: "Sangam Period", theme: ["Justice", "Dharma", "Moral Integrity"], summary: "A king executes his own son to grant justice to a cow whose calf was killed, exemplifying the impartial nature of ancient Tamil dharma." },
  { id: "tm-6", title: "Kannagi as Pattini", region: Region.Tamil, type: "Goddess Legend", era: "Post-Sangam", theme: ["Female Power", "Protection", "Wrath"], summary: "Follows Kannagi's evolution into village goddess forms, emphasizing divine female rage and protection from evil." },
  { id: "tm-7", title: "Nallathangal", region: Region.Tamil, type: "Tragic Folk Legend", era: "Medieval", theme: ["Sibling Love", "Sacrifice", "Tragedy"], summary: "A woman drowns herself and her children after being mistreated by in-laws, becoming a symbol of tragic sacrifice and sibling devotion." },
  { id: "tm-8", title: "Aiyanar Guardian Legends", region: Region.Tamil, type: "Guardian Deity Folklore", era: "Ancient", theme: ["Protection", "Justice", "Rural Faith"], summary: "Stories of a fierce horse-riding deity who protects villages, reflecting ancient pre-Vedic protective traditions." },
  { id: "tm-9", title: "Mariamman Legends", region: Region.Tamil, type: "Mother Goddess Folklore", era: "Ancient", theme: ["Healing", "Fertility", "Divine Wrath"], summary: "A powerful goddess who protects communities from disease, often portrayed as a wronged woman turned divine healer." },
  { id: "tm-10", title: "Manimekalai's Renunciation", region: Region.Tamil, type: "Philosophical Epic", era: "2nd–5th Century CE", theme: ["Karma", "Compassion", "Renunciation"], summary: "The story of Kovalan's daughter who becomes a Buddhist nun, exploring compassion and the high moral ground of Tamil Buddhist philosophy." }
];
